### PR TITLE
Add event details, WATM hero [WIP]

### PR DESCRIPTION
**Pull request by shinedesigns**

### CODE REVIEW

**Comment by j00bar** [comment]
@shinedesigns 

1. You need to rebase, please. This cannot be merge as is.
2. The assets need to be optimized. The Jacobs bio image is over 6MB. The Vanek one is nearly 4MB. Those are examples, not an exhaustive list - the entire page load for WATM is over 35MB! Given that we don't paint the page until all of the assets are loaded and most of our users come in over mobile, it needs to be far smaller.
3. It doesn't need to be fixed before merge, but the spacing of the Zoom links relative to time slot needs some attention on mobile: 
image
4. While we're on the subject of assets that need to be optimized, the WATM banner on the homepage is 3.5MB. The homepage is presently 8MB! It doesn't need to be part of this PR, but several of the partner logos are the bulk of that weight - Buncombe County HHS is 1.7MB. There are several that are 250K or so.

**Comment by shinedesigns** [comment]
Got it. I can optimize and lazy-load images.

**Comment by shinedesigns** [comment]
That was on the “roadmap” for after this event (CMS integration and performance optimizations — most notably images), but agreed that 35MB is unworkable on mobile.

**Comment by shinedesigns** [comment]
3. is a known issue to be resolved with my "add to calendar" commit(s) today

**Pull request merged**
