### PR TITLE
Content: Events page changes

### PR DESCRIPTION
**Pull request by shredtechular**
This PR addresses #94.

This update includes the content & styling changes that were outlined in #94.  I will leave a comment in that issue for integrating the Eventbrite page into the site as I believe that effort is separate from an initial page layout and content update.  Everything else is pretty straight forward with this update however.  

One minor note to point out is that the issue described having the June 14th issue under the "Upcoming Events" section, however, that has obviously passed now, so I included this in the past events section.

### Desktop
screencapture-localhost-4000-upcoming-events-2018-06-30-20_46_56

### Mobile
screencapture-localhost-4000-upcoming-events-2018-06-30-20_47_11

### CODE REVIEW

**Comment by j00bar** [comment]
Looks good - holding off on merge pending some clarifications from Jennifer.

**Comment by howtohumanbetter** [comment]
asheville oad 2018

image for Overdose Awareness Day event

**Comment by j00bar** [comment]
Couple of tweaks:

1. Events that are now past should be listed in past.
2. The dates for the listener training should match those in #114 
3. The image for the Overdose Awareness Day should be derived from the asset Jennifer attached above.

Thanks so much!!

**Comment by j00bar** [comment]
Also, past events shouldn't have RSVP buttons, but upcoming ones can/should :+1:

**Pull request merged**
